CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int DEFAULT 2,
  "email" varchar UNIQUE,
  "password" varchar,
  "name" varchar,
  "email_verified_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "remember_token" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "personals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "phone_number" varchar,
  "mobile_number" varchar,
  "sex" sex,
  "birth_date" date,
  "religion" religion,
  "passport_number" varchar UNIQUE,
  "passport_expiry_date" date,
  "marital_status" maritalstatus DEFAULT 'single',
  "nationality" varchar,
  "country" varchar,
  "province" varchar,
  "city" varchar,
  "address" TEXT,
  "postal_code" varchar,
  "photo" varchar,
  "blood_type" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "schools" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "address" text,
  "country" varchar,
  "province" varchar,
  "city" varchar,
  "state" varchar,
  "zip_code" varchar,
  "phone" varchar,
  "email" varchar,
  "graduation_year" smallint,
  "gpa" decimal(2,2),
  "gpa_max" decimal(2,2),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "documents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "legal_document" varchar,
  "financial_document" varchar,
  "medical_document" varchar,
  "parental_document" varchar,
  "passport_document" varchar,
  "passport_copy_document" varchar,
  "certificate_document" varchar,
  "transcript_document" varchar,
  "cv_document" varchar,
  "english_certificate_document" varchar,
  "essay_document" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "emergency_contacts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "relationship" varchar,
  "address" text,
  "phone" varchar,
  "mobile" varchar,
  "email" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "date" date
);

CREATE TABLE "provinces" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "cities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "province_id" int,
  "name" varchar,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "districts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" int,
  "name" varchar,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "admissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "program_id" int,
  "reg_number" varchar UNIQUE,
  "status" statusadmission,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "log_admissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admission_id" int,
  "program_id" int,
  "reg_number" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "program_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "insurances" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "validity" varchar,
  "cover" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "accommodations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "contact_person" varchar,
  "phone" varchar,
  "address" text,
  "need_accommodation" boolean,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "home_institutions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "address" text,
  "phone_number" varchar,
  "email" varchar,
  "website" varchar,
  "department" varchar,
  "start_year" smallint,
  "gpa" decimal(2,2),
  "gpa_max" decimal(2,2),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "programs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_id" int,
  "code" varchar UNIQUE,
  "name" varchar,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "english_tests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "score" decimal(2,2),
  "test_center" varchar,
  "test_date" date,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "proposed_studies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "progress" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "score" decimal,
  "admission" boolean,
  "personal" boolean,
  "schools" boolean,
  "accommodation" boolean,
  "english_test" boolean,
  "emergency_contact" boolean,
  "document" boolean,
  "all_submit" boolean,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "social_medias" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "icon" varchar,
  "name" varchar,
  "link" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_home_sliders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filename" varchar,
  "title" varchar,
  "description" text,
  "link" text,
  "is_active" boolean,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_calendars" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event" varchar,
  "event_date" date,
  "start" time,
  "end" time,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_testimonials" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "title" varchar,
  "description" text,
  "photo" varchar,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_abouts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_vice_rectors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "photo" varchar,
  "content" text,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_teams" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar,
  "name" varchar,
  "title" varchar,
  "photo" varchar,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_international_collaborations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "photo" varchar,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_partners" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "regional" varchar,
  "website" varchar,
  "logo" varchar,
  "country" varchar,
  "address" text,
  "description" text,
  "english_profiency" text,
  "eligible_departement" text,
  "study_periode" text,
  "fact_sheet" varchar,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_collaborates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "partnership_booklet" varchar,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_outbounds" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_outbound_sliders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filename" varchar,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_uper_sa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "program_detail" text,
  "requirement" text,
  "flowchart" varchar,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_iisma" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_iisma_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filename" varchar,
  "host_university" varchar,
  "year" smallint,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_inbounds" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_inbound_sliders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filename" varchar,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_inbound_internship_attachments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_student_exchanges" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "updated_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "page_news" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "slug" varchar UNIQUE,
  "content" text,
  "cover" varchar,
  "created_by" int,
  "updated_by" int,
  "is_publish" boolean,
  "is_highlight" boolean,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "personals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "schools" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "documents" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "emergency_contacts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cities" ADD FOREIGN KEY ("province_id") REFERENCES "provinces" ("id");

ALTER TABLE "districts" ADD FOREIGN KEY ("city_id") REFERENCES "cities" ("id");

ALTER TABLE "admissions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "admissions" ADD FOREIGN KEY ("program_id") REFERENCES "programs" ("id");

ALTER TABLE "log_admissions" ADD FOREIGN KEY ("admission_id") REFERENCES "admissions" ("id");

ALTER TABLE "insurances" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "accommodations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "home_institutions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "programs" ADD FOREIGN KEY ("type_id") REFERENCES "program_types" ("id");

ALTER TABLE "english_tests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "proposed_studies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "progress" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "page_home_sliders" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_home_sliders" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_calendars" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_calendars" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_testimonials" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_testimonials" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_abouts" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_vice_rectors" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_teams" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_teams" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_international_collaborations" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_partners" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_partners" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_collaborates" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_outbounds" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_outbound_sliders" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_outbound_sliders" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_uper_sa" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_iisma" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_iisma_images" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_iisma_images" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_inbounds" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_inbound_sliders" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_inbound_sliders" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_inbound_internship_attachments" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_student_exchanges" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_news" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "page_news" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");